services:
  crm-app:
    image: djcrm:1
    container_name: crm-app
    environment:
      - DBNAME=crm
      - DBUSER=crm
      - DBPASSWORD=crm
      - DBHOST=crm-db
      - DBPORT=5432
      - ENV_TYPE=development
      #Following veriables   are needed for the docker image
      - SECRET_KEY= mco934$@)NHUYTC%6789
      - DEFAULT_FROM_EMAIL=your_email@example.com
      - ADMIN_EMAIL=your_admin_email@example.com
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
      - DOMAIN_NAME="DOMAIN.NAME"
      - SWAGGER_ROOT_URL="SWAGGER.ROOT.URL"
    command: /app/celery -A crm worker -l info
    depends_on:
      - crm-db
      - redis
    ports:
      - 8000:8000
    volumes:
      - C:/Django-CRM:/app
    networks:
      - nw
  
  redis:
      image: redis:latest
      ports:
      - 6379:6379
      container_name: redis

  celery:
    image: celery:latest
    volumes:
      - C:/Django-CRM:/app
    container_name: cl01
    environment:
      CELERY_BROKER_URL: "redis://redis"
      CELERY_BACKEND_URL: "redis://redis"
    links:
      - redis

  crm-db:
    image: postgres:latest
    container_name: crm-db
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=crm
    ports:
      - 5432:5432
    volumes:
      - C:/postgresql:/var/run/postgresql # Updated local file path for windows hosts
    networks:
      - nw

#  celery:
#    image: celery:latest
#    volumes:
#      - C:/Django-CRM:/app
#    depends_on:
#      - redis
  # redis:
  #     image: redis:latest
  #     ports:
  #     - 6379:6379
  #     container_name: redis
  
  # celery:
  #   image: celery:latest
  #   volumes:
  #     - C:/Django-CRM:/app
  #   container_name: cl01
  #   environment:
  #     CELERY_BROKER_URL: "redis://redis"
  #     CELERY_BACKEND_URL: "redis://redis"
  #   links:
  #     - redis

networks:
  nw: {}